### ISSUE TITLE
Unable to remove role exclusions from authorities 

### ISSUE THREAD

**Issue by bleeper913** [NucleoidMC/leukocyte#1]
I'm interested in using Leukocyte in conjunction with player-roles, as I would absolutely love their ability to integrate together. But I've run into a bit of a snag when I try to change exclusions based on roles for authorities. 

I set an authority with only one rule 

`/protect set rule example portals deny`

I verify that no players can ignite portals within the authority.

And to that authority I add an exclusion for a role known as `trusted`.

`/protect exclusion add example role trusted`

However, I've decided I no longer wish to exclude players who are `trusted` from the authority. But the command to remove exclusions only seems to accept player names, and returns an error when I try to remove exclusions for roles.

For example when I try `/protect exclusion remove example trusted`, I get the message `That player does not exist`, and the `trusted` role is still excluded from the authority.

Perhaps it's something simple I've overlooked but I wanted to post this here to see if anyone else had reported similar findings.

**Comment by Gegy** [comment]
Thanks for the report! I totally missed this 😅 
Essentially this comes from there being ambiguity between the two arguments such that it can't tell which is being selected. This is fixable by adding clarification like with the add command. :)

**Comment by Gegy** [comment]
Have released [0.1.2](https://github.com/NucleoidMC/leukocyte/releases/tag/0.1.2) to resolve this issue :)

**Comment by bleeper913** [comment]
That's fantastic! I really appreciate the quick response. Cheers!
