### ISSUE TITLE
Leukocyte forcefully creating a protection around world spawn to all players

### ISSUE THREAD

**Issue by pixiescale** [NucleoidMC/leukocyte#39]
I've already removed every single authority from my server and yet whenever i set a world spawn, everything around it becomes impossible to break, place, interact, attack, spawn, what's going on??

**Comment by haykam821** [comment]
Are you sure the vanilla spawn protection is not enabled?

**Comment by pixiescale** [comment]
how can i disable this

**Comment by pixiescale** [comment]
i already found the setting, can you delete this thread i have no idea how this site works
