### ISSUE TITLE
When creating a shape the coordinates are jumbled

### ISSUE THREAD

**Issue by Viotomix** [NucleoidMC/leukocyte#49]
![grafik](https://user-images.githubusercontent.com/81643739/187988205-10e3ebfe-736c-47dd-93cc-d0080d6e7a66.png)

Regardless of if I try to protect an area via creating an authority and giving it the coords there or if I try to create a shape, the coordiantes are jumbled and I can't select the area I need.

Using version 0.3.4

The coordinates seem to be sorted with the smaller numbers all in min and the bigger numbers all in max

**Comment by haykam821** [comment]
In Minecraft, boxes always use the lowest coordinates for their minimum and the highest coordinates for their maximum. Effectively, a box from (108, 88, 341) to (200, 62, 243) is the same as a box from (108, 62, 243) to (200, 88, 341). This issue won't cause any mechanical problems.

**Comment by Viotomix** [comment]
Yeah actually you're right, then I have an entirely different issue, which would be that when I create an authority and then test for the authority in the given area it tells me there isn't one. Did I miss a step somehow?

**Comment by Viotomix** [comment]
![grafik](https://user-images.githubusercontent.com/81643739/187992082-10640d4e-a6fe-4b34-9eb9-03c38e24aa5c.png)
![grafik](https://user-images.githubusercontent.com/81643739/187992107-4502751c-24bc-4f1e-85e5-0d8d83ea95ef.png)
In case I sound like I'm a complete numbnut, I'm supposedly in the authority, but when I tests for one it says I'm not

**Comment by Restioson** [comment]
> the authority IS applied in the area, it just says it's not

Should a second issue be opened for this?

**Comment by Viotomix** [comment]
> Should a second issue be opened for this?

[Done](https://github.com/NucleoidMC/leukocyte/issues/50#issue-1360508057)
Sorry it took so long, I didn't have the time to do it last night
